# -*- coding: utf-8 -*-
"""Miller_Kimberley_PythonCode_ITT103_S2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEVt2xYRcSYb7I_agvoij2T1Bxk0L9Gk
"""

"""
- Author: Kimberley Miller
- Date Created:April 28, 2022
- Course: ITT103
-Purpose: The assignment is to write a pseudocode algorithm for the problem using the necessary requitrements. JamEx Limited requires a program to calculate and print the commission received by a salesperson
"""

"""
JamEx Limited requires a program to calculate and print the commission received by a
salesperson. The program should process an undetermined number of salespersons and 
appropriately terminate by a predefined input. The commission rate is based on two factors, 
the amount of sales and the class to which a salesperson belongs. The input will be the 
salesperson number, sales amount and class. The commission rate will be based on the 
following criteria:

Class=1
If sales is equal to or less than $1000, the rate is 6 percent.
If sales is greater than $1000 but less than $2000, the rate is 7 percent.
If the sales is $2000 or greater, the rate is 10 percent.

Class=2
If the sales is less than $1000, the rate is 4 percent.
If the sales is $1000 or greater, the rate is 6 percent.

Class=3
The rate is 4.5 percent for all sales amount

Class=any other value
Output an appropriate error message.
"""

classrate_1a = 0.06
classrate_1b = 0.07 
classrate_1c = 0.10 
classrate_2a = 0.04 
classrate_2b= 0.06 
classrate_3 = 0.045

commission_rate = 0 

def output_results (number, salesclass, amount, rate):   
   
    print("********************************")
    print("////////// R E S U L T //////////")
    print("/////////////////////////////////")
    print("\nSalesperson number:" + str(number))
    print("salesperson class: " + str(salesclass))
    print("sales amount: $" + str(amount))
    print("comission rate: $" + str(round(rate, 2)))
    print("\n**********************************")
  

while True:
    while True:     
        message = input("Welcome to JamEx Limited commission calculator program.  \nPlease enter stop to exit the program. To continue, enter go:  ")
        if message == 'go':
            break           
        elif message == 'Stop' or message == 'stop':
            print("Program has ended. \nThank you for using JamEx Limited commission calculator program. \nHope to see you again:) ")
            break
        else:
            print("Sorry,the class is invalid\n")
    
    if message == 'Stop' or message == 'stop':
        break 
    
    salesperson_numb = input("\nInput the salesperson number: ")
    sales_amt = int(input("\nInput the sales amount: "))
    
    while True:
        try:
            salesperson_class = int(input("\nInput the salesperson class: "))      
        except ValueError:
            print("Sorry,the class is invalid.")
    
            continue
        if salesperson_class < 1 or salesperson_class > 3:
            print("That class is not valid. please enter from class 1-3 :)")  
        else:    
           
            break
        
    if salesperson_class == 1:
        if sales_amt <= 1000:
            commission_rate = classrate_1a * sales_amt
        elif sales_amt > 1000 and sales_amt < 2000:
            commission_rate = classrate_1b * sales_amt
        elif sales_amt >= 2000:
            commission_rate = classrate_1a * sales_amt

    if salesperson_class == 2:
        if sales_amt < 1000:
            commission_rate = classrate_2a * sales_amt
        elif sales_amt >= 1000:
            commission_rate = classrate_2b * sales_amt

    if salesperson_class == 3:
        commission_rate = classrate_3 * sales_amt
    
    output_results(salesperson_class , salesperson_numb ,sales_amt, commission_rate)

